---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -ex
  yamllint .
  ansible-lint .
  flake8
platforms:
  - name: instance
    image: centos:7
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: /usr/sbin/init
    capabilities:
      - ALL
    privileged: true
    pull: false
    groups:
      - docker
provisioner:
  name: ansible
scenario:
  test_sequence:
  - lint
  - destroy
  - syntax
  - create
  - prepare
  - converge
  - destroy
verifier:
  name: ansible
